jobs:
  check-azure-ci-and-add-commit-status:
    if: 'github.event.issue.pull_request != null &&

      github.event.comment.user.login == ''hudi-bot''

      '
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v2
    - continue-on-error: true
      id: check_pr_state
      name: Check PR state
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: "const issueNumber = context.issue.number;\nconst { data: pullRequest\
          \ } = await github.rest.pulls.get({\n  owner: context.repo.owner,\n  repo:\
          \ context.repo.repo,\n  pull_number: issueNumber\n});\n\n// Only check open\
          \ PRs and a PR that is not a HOTFIX\nconst shouldSkip = (pullRequest.body.includes('HOTFIX:\
          \ SKIP AZURE CI')\n  || pullRequest.state != 'open');\n\nif (!shouldSkip)\
          \ {\n  const commitHash = pullRequest.head.sha;\n  console.log(`Latest commit\
          \ hash: ${commitHash}`);\n  // Set the output variable to be used in subsequent\
          \ step\n  core.setOutput(\"latest_commit_hash\", commitHash);\n}\nconsole.log(`Should\
          \ skip Azure CI? ${shouldSkip}`);\nreturn shouldSkip;\n"
    - continue-on-error: true
      if: steps.check_pr_state.outputs.result != 'true'
      name: Check Azure CI report and create commit status to PR
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: "const latestCommitHash = '${{ steps.check_pr_state.outputs.latest_commit_hash\
          \ }}'            \nconst issueNumber = context.issue.number;\nconst checkAzureCiAndCreateCommitStatus\
          \ = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/azure_ci.js`);\n\
          \nawait checkAzureCiAndCreateCommitStatus({\n  github,\n  context,\n  prNumber:\
          \ issueNumber,\n  latestCommitHash: latestCommitHash\n});\n"
name: Azure CI
on:
  repository_dispatch:
    types: trigger-ga___azure_ci_check.yml
permissions:
  issues: read
  pull-requests: read
  statuses: write
