env:
  MVN_ARGS: -e -ntp -B -V -Dgpg.skip -Djacoco.skip -Pwarn-log -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.shade=warn
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.dependency=warn -Dmaven.wagon.httpconnectionManager.ttlSeconds=25
    -Dmaven.wagon.http.retryHandler.count=5
  SPARK_COMMON_MODULES: hudi-spark-datasource/hudi-spark,hudi-spark-datasource/hudi-spark-common
jobs:
  validate-release-candidate-bundles:
    env:
      HUDI_VERSION: 0.14.1
      STAGING_REPO_NUM: 1123
    if: false
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        architecture: x64
        cache: maven
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      env:
        FLINK_PROFILE: ${{ matrix.flinkProfile }}
        SCALA_PROFILE: ${{ matrix.scalaProfile }}
        SPARK_PROFILE: ${{ matrix.sparkProfile }}
        SPARK_RUNTIME: ${{ matrix.sparkRuntime }}
      name: IT - Bundle Validation - OpenJDK 8
      run: './packaging/bundle-validation/ci_run.sh hudi_docker_java8 $HUDI_VERSION
        openjdk8 $STAGING_REPO_NUM

        '
    - continue-on-error: true
      env:
        FLINK_PROFILE: ${{ matrix.flinkProfile }}
        SCALA_PROFILE: ${{ matrix.scalaProfile }}
        SPARK_PROFILE: ${{ matrix.sparkProfile }}
        SPARK_RUNTIME: ${{ matrix.sparkRuntime }}
      if: ${{ env.SPARK_PROFILE >= 'spark3' }}
      name: IT - Bundle Validation - OpenJDK 11
      run: './packaging/bundle-validation/ci_run.sh hudi_docker_java11 $HUDI_VERSION
        openjdk11 $STAGING_REPO_NUM

        '
    - continue-on-error: true
      env:
        FLINK_PROFILE: ${{ matrix.flinkProfile }}
        SCALA_PROFILE: ${{ matrix.scalaProfile }}
        SPARK_PROFILE: ${{ matrix.sparkProfile }}
        SPARK_RUNTIME: ${{ matrix.sparkRuntime }}
      if: ${{ env.SPARK_PROFILE >= 'spark3.3' }}
      name: IT - Bundle Validation - OpenJDK 17
      run: './packaging/bundle-validation/ci_run.sh hudi_docker_java17 $HUDI_VERSION
        openjdk17 $STAGING_REPO_NUM

        '
    strategy:
      matrix:
        include:
        - flinkProfile: flink1.18
          scalaProfile: scala-2.13
          sparkProfile: spark3.5
          sparkRuntime: spark3.5.0
        - flinkProfile: flink1.18
          scalaProfile: scala-2.12
          sparkProfile: spark3
          sparkRuntime: spark3.5.0
        - flinkProfile: flink1.18
          scalaProfile: scala-2.12
          sparkProfile: spark3.5
          sparkRuntime: spark3.5.0
        - flinkProfile: flink1.18
          scalaProfile: scala-2.12
          sparkProfile: spark3.4
          sparkRuntime: spark3.4.0
        - flinkProfile: flink1.17
          scalaProfile: scala-2.12
          sparkProfile: spark3.3
          sparkRuntime: spark3.3.2
        - flinkProfile: flink1.16
          scalaProfile: scala-2.12
          sparkProfile: spark3.3
          sparkRuntime: spark3.3.1
        - flinkProfile: flink1.15
          scalaProfile: scala-2.12
          sparkProfile: spark3.2
          sparkRuntime: spark3.2.3
        - flinkProfile: flink1.14
          scalaProfile: scala-2.12
          sparkProfile: spark3.1
          sparkRuntime: spark3.1.3
        - flinkProfile: flink1.14
          scalaProfile: scala-2.12
          sparkProfile: spark3.0
          sparkRuntime: spark3.0.2
        - flinkProfile: flink1.14
          scalaProfile: scala-2.11
          sparkProfile: spark
          sparkRuntime: spark2.4.8
        - flinkProfile: flink1.14
          scalaProfile: scala-2.11
          sparkProfile: spark2.4
          sparkRuntime: spark2.4.8
name: Release Candidate Validation
on:
  repository_dispatch:
    types: trigger-ga___release_candidate_validation.yml
