jobs:
  process-new-and-updated-prs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Process new and updated PRs
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: "// Cron schedule may not be reliable so giving buffer time to avoid\
          \ missing recent PRs\nconst since = new Date(new Date().getTime() - (900\
          \ * 1000)).toISOString();\nconst query = `repo:${context.repo.owner}/${context.repo.repo}\
          \ type:pr state:open updated:>=${since}`;\nconst openPrs = await github.paginate(github.rest.search.issuesAndPullRequests,\
          \ {\n  q: query,\n  sort: 'updated',\n  order: 'desc',\n  per_page: 100\n\
          });\n\nconst { labelDocsPr, labelPrWithSize } = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/labeler.js`);\n\
          const checkAzureCiAndCreateCommitStatus = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/azure_ci.js`);\n\
          \nconsole.log(`Number of PRs to process: ${openPrs.length}`);\n\nfor (const\
          \ pr of openPrs) {\n  console.log(`*** Processing PR: ${pr.title}, URL:\
          \ ${pr.html_url}`);\n\n  const { data: pullRequest } = await github.rest.pulls.get({\n\
          \    owner: context.repo.owner,\n    repo: context.repo.repo,\n    pull_number:\
          \ pr.number\n  });\n\n  const targetBase = pullRequest.base.ref;\n  console.log(`Target\
          \ base branch: ${targetBase}`);\n\n  // Label docs PR (targeting \"asf-site\"\
          \ branch)\n  if (targetBase === 'asf-site') {\n    await labelDocsPr({\n\
          \      github,\n      context,\n      prNumber: pr.number\n    });\n  }\n\
          \n  // Label PR size\n  await labelPrWithSize({\n    github,\n    context,\n\
          \    prNumber: pr.number,\n    prData: pullRequest\n  });\n\n  // Check\
          \ Azure CI and create commit status (targeting \"master\", \"release*\"\
          , or \"branch-0.x\" branch)\n  const targetBaseRegex = /^(master|release.*|branch-0\\\
          .x)$/;\n  if (targetBaseRegex.test(targetBase)\n    && !pr.body.includes('HOTFIX:\
          \ SKIP AZURE CI')) {\n    const latestCommitHash = pullRequest.head.sha;\n\
          \n    // Create commit status based on Azure CI report to PR\n    await\
          \ checkAzureCiAndCreateCommitStatus({\n      github,\n      context,\n \
          \     prNumber: pr.number,\n      latestCommitHash: latestCommitHash\n \
          \   });\n  }\n}\n"
name: Scheduled Workflow
on:
  repository_dispatch:
    types: trigger-ga___scheduled_workflow.yml
permissions:
  issues: read
  pull-requests: write
  statuses: write
