jobs:
  run-tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-python@v3
    - continue-on-error: true
      name: run script
      run: python3 scripts/pr_compliance.py run-tests > test.log || { echo "::error::pr_compliance.py
        $(cat test.log)" && exit 1; }
name: Update Pr Compliance
on:
  repository_dispatch:
    types: trigger-ga___update_pr_compliance.yml
